# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba9985aee3f132416e2aee6ab0be9b6bc61555a2efc6bd7b093f72748d1e19e248c75d607951a76e2d3009b8f915478c983bf234c65e457b588b8ac8bc11452

test:
  secret_key_base: 05941b6428e68518cb623ca6abe97703a6713248e57deea299716f1d2411a9d305a37c2555e78804218ff7a84f6314a17ee3e3c56a9b92e4448b8060ecd941c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
